var omnitech;
(function(c){(function(c){(function(f){var c=function(){function b(){this.cols=[];this.having=[new d(null)];this.where=[new d(null)];this.group=[new d(null)]}b.prototype.aggregations=function(){var a=[];this.cols.forEach(function(b){b.isAggregation()&&a.push(b)});return a};return b}();f.Statement=c;c=function(){function b(a,b){this.name=a;this.desc=b?b:a}b.prototype.emitString=function(){return this.name};b.prototype.isAggregation=function(){return!1};b.prototype.toString=function(){return this.emitString()};return b}();
f.Column=c;c=function(){function b(){}b.prototype.emitString=function(){return this.agg&&this.expr?this.agg+"("+this.expr+")":"aggregation"};b.prototype.isAggregation=function(){return!0};b.prototype.toString=function(){return this.emitString()};return b}();f.Aggregation=c;c=function(){function b(a){this.parent=a;this.operator="Greater Than"}b.prototype.emitString=function(){return this.left.emitString()+this.operator+this.right.emitString()};b.prototype.isAggregation=function(){return!1};b.prototype.isLeaf=
function(){return!0};b.prototype.toString=function(){return this.emitString()};return b}();f.Condition=c;var d=function(){function b(a){this.parent=a;this.conditions=[];this.groups=[];this.isAncestor=!1;this.binOperator="and";null===a&&(this.isAncestor=!0)}b.prototype.emitString=function(){return"()"};b.prototype.isAggregation=function(){return!1};b.prototype.isLeaf=function(){return!0};b.prototype.toString=function(){return this.emitString()};return b}();f.ConditionGroup=d})(c.reports||(c.reports=
{}))})(c.js||(c.js={}))})(omnitech||(omnitech={}));(function(c){(function(c){(function(c){var g=function(){function d(){}d.injection=function(){return[d]};d.prototype.getColumns=function(){return d.reportColumns?d.createColumns(d.reportColumns):[new c.Column("name"),new c.Column("district"),new c.Column("village"),new c.Column("school"),new c.Column("girl_number"),new c.Column("boy_number"),new c.Column("is_government_owned"),new c.Column("is_national")]};d.prototype.generateReport=function(b,a){return d.generateReportCallback?d.generateReportCallback(b,
a):!1};d.extendObject=function(b,a){var c;if(b===a)return b;for(c in a)b[c]=a[c];return b};d.createColumns=function(b){return b.map(function(a){return 1<a.length?new c.Column(a[0],a[1]):new c.Column(a[0])})};return d}();c.DataLoader=g})(c.reports||(c.reports={}))})(c.js||(c.js={}))})(omnitech||(omnitech={}));(function(c){(function(c){(function(c){var g=function(){function b(a,b,h){var e=this;this.$scope=a;this.dataLoader=b;this.filterFilter=h;a.columns=b.getColumns();a.statement=new c.Statement;a.addAggregation=function(){return e.addAggregation()};a.removeAggregation=function(a){return e.removeAggregation(a)};a.addConditionGroup=function(a){return e.addConditionGroup(a)};a.addCondition=function(a){return e.addCondition(a)};a.deleteCondition=function(a){return e.deleteCondition(a)};a.deleteConditionGroup=
function(a){return e.deleteConditionGroup(a)};a.showStatement=function(){b.generateReport(d.getReturnStatement(a.statement),d.generateWhereStatement(a.statement.where[0]))};a.$watch("columns",function(){return e.onColumnsChanged()},!0)}b.injection=function(){return["$scope","dataLoader","filterFilter",b]};b.prototype.onColumnsChanged=function(){var a=this.filterFilter(this.$scope.columns,{selected:!0}),b=this.$scope.statement;b.cols=b.cols.filter(function(a){return a.isAggregation()});this.addItemsIfAbsent(b.cols,
a)};b.prototype.addItemsIfAbsent=function(a,b){b.forEach(function(b){0>a.indexOf(b)&&a.unshift(b)})};b.prototype.addAggregation=function(){this.$scope.statement.cols.push(new c.Aggregation)};b.prototype.removeAggregation=function(a){var b=this.$scope.statement.cols;b.splice(b.indexOf(a),1)};b.prototype.addConditionGroup=function(a){var b=new c.ConditionGroup(a);a.groups.push(b);this.addCondition(b);return b};b.prototype.addCondition=function(a){var b=new c.Condition(a);a.conditions.push(b);return b};
b.prototype.deleteCondition=function(a){this.deleteItem(a.parent.conditions,a)};b.prototype.deleteConditionGroup=function(a){this.deleteItem(a.parent.groups,a)};b.prototype.deleteItem=function(a,b){var c=a.indexOf(b);a.splice(c,1)};b.randomString=function(){return Math.random().toString(36).substring(7)};return b}();c.ReportCtrl=g;var d=function(){function b(){}b.generateWhereStatement=function(a){if(!a||!a.binOperator||!a.conditions)return"";var c="";a.groups&&0<a.groups.length&&(c="("+a.groups.map(function(a){return"("+
b.generateWhereStatement(a)+")"}).reduce(function(b,c){return b+" "+a.binOperator+" "+c})+")");var d="";0<a.conditions.length&&(d=a.conditions.map(function(a){return b.generateConditionStatement(a)}).reduce(function(b,c){return b+" "+a.binOperator+" "+c}));return c?d?"("+d+") "+a.binOperator+" "+c:c:d};b.generateConditionStatement=function(a){if(!a.left||!a.operator||!a.right)return"";var c=a.left.toString(),d=a.right.toString(),e=b.getSign(a.operator);return e?c+" "+e+" "+d:a.operator+"("+c+", "+
d+")"};b.getSign=function(a){return{"Less Than":"<","Less Than or Equal":"<=","Equal to":"=","Not Equal":"!=","Greater Than":">","Greater Than Or Equal":">="}[a]};b.getReturnStatement=function(a){return a&&a.cols&&0!==a.cols.length?a.cols.map(function(a){return a.toString()}).reduce(function(a,b){return a+","+b}):""};return b}();c.QueryGenerator=d})(c.reports||(c.reports={}))})(c.js||(c.js={}))})(omnitech||(omnitech={}));(function(c){c=c.js||(c.js={});c=c.reports||(c.reports={});angular.module("omnitechApp",["ngAnimate"]).controller("ReportCtrl",c.ReportCtrl.injection()).service("dataLoader",c.DataLoader.injection())})(omnitech||(omnitech={}));
